import localFont from "next/font/local";
import "./globals.css";
import { DeviceIdProvider } from "./providers/DeviceIdProvider";
import UIProvider from "./providers/UIProvider";
import ReactQueryProvider from "./providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { ThemeProvider } from "./providers/ThemeProvider";

export const metadata = {
  title: "Pixel Guess",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          enableColorScheme
        >
          <Toaster />
          <DeviceIdProvider>
            <UIProvider>
              <ReactQueryProvider>
                <main className="mx-auto flex flex-col justify-between w-full h-full max-w-4xl px-6 py-12 lg:px-8 min-h-screen">
                  {children}
                  <Footer />
                </main>
              </ReactQueryProvider>
            </UIProvider>
          </DeviceIdProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
