import Header from "@/components/Header";
import prisma from "@/lib/prisma";
import { notFound } from "next/navigation";

export const metadata = {
  title: "Pixel Guess",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const categorySlug = (await params).categorySlug;
  const category = await prisma.category.findFirst({
    where: {
      slug: categorySlug,
    },
  });

  if (!category) {
    notFound();
  }

  return (
    <>
      <Header category={category} />
      {children}
    </>
  );
}
